INFO_MODEL='_ANF5HG_1648D';
INFO_VENDOR='I3DVR';
INFO_DVRREADY='2';
INFO_DVRSTATUS='1';
INFO_DVRCHANNEL='16';
INFO_DISCONNECTRESON='0';
INFO_LANGUAGE='ENGLISH';
INFO_TIMEZONE='7';
INFO_DATEFORMAT='1';
INFO_TIMEFORMAT='1';
INFO_DST='1';
INFO_CAMTYPE='NTSC';
INFO_RTSPPORT='5554';
INFO_SYSTEM_SECURITY_AUDIO='1';
INFO_SYSTEM_SECURITY_DOUBLE_LOGIN='0';
INFO_SYSTEM_SECURITY_CHECK_PASSWORD='0';
INFO_SYSTEM_SECURITY_ID_INPUT='1';
INFO_SYSTEM_SECURITY_ENHANCED_ID='1';
INFO_COVERTCH[0]='0';
INFO_COVERTCH[1]='0';
INFO_COVERTCH[2]='0';
INFO_COVERTCH[3]='0';
INFO_COVERTCH[4]='0';
INFO_COVERTCH[5]='0';
INFO_COVERTCH[6]='0';
INFO_COVERTCH[7]='0';
INFO_COVERTCH[8]='0';
INFO_COVERTCH[9]='0';
INFO_COVERTCH[10]='0';
INFO_COVERTCH[11]='0';
INFO_COVERTCH[12]='0';
INFO_COVERTCH[13]='0';
INFO_COVERTCH[14]='0';
INFO_COVERTCH[15]='0';
INFO_CAMTITLE[0]='CAM1';
INFO_CAMTITLE[1]='CAM2';
INFO_CAMTITLE[2]='CAM3';
INFO_CAMTITLE[3]='CAM4';
INFO_CAMTITLE[4]='CAM5';
INFO_CAMTITLE[5]='CAM6';
INFO_CAMTITLE[6]='CAM7';
INFO_CAMTITLE[7]='CAM8';
INFO_CAMTITLE[8]='CAM9';
INFO_CAMTITLE[9]='CAM10';
INFO_CAMTITLE[10]='CAM11';
INFO_CAMTITLE[11]='CAM12';
INFO_CAMTITLE[12]='CAM13';
INFO_CAMTITLE[13]='CAM14';
INFO_CAMTITLE[14]='CAM15';
INFO_CAMTITLE[15]='CAM16';
INFO_CAMTITLE_ON='1';
INFO_EVENTICON_ON='1';
INFO_BORDER_COLOR='1';
INFO_EXISTDISK='9766';
INFO_ALARM_SENSOR={ain_cam:00,ain_dvr:16,aout_cam:00,aout_dvr:16};
INFO_AUDIO_SUPPORT='1';
INFO_SNAPSHOT_SUPPORT='1';
INFO_ID_INPUT_MODE='0';
INFO_ENHANCED_PASSWORD='0';
INFO_ENHANCED_USER_ID='0';
INFO_PASSWORD_CHECK='0';
INFO_DUAL_LOGIN='0';
var LANGLIST = {'ENGLISH': 'english','KOREAN': 'korean','JAPANESE': 'japanese','RUSSIAN': 'russian','ITALIAN': 'italian','FRENCH': 'french','GERMAN': 'german','POLISH': 'polish','THAI': 'thai','SPANISH': 'spanish','CHINESE(T)': 'chinese(t)','DUTCH': 'dutch','CZECH': 'czech'};
INFO_PASSWD_CHANGED='0';

INFO_AUDIO_IN_COUNT='16';

INFO_AUDIO_IN_IPCAM_COUNT='16';

INFO_CAMERA_INSTALL_MODE='1';
SUPPORT_OPENMODE='0';

INFO_IPSETSUPPORT='1';

INFO_ZOOM_PIP_DURATION='0';

INFO_TAMPER_SUPPORT=false;

INFO_DMVA_SUPPORT=false;

INFO_USE_MOBILE_PUSH=false;

INFO_USE_SEQURINET=false;

INFO_USE_SEARCH_IP_CONFLICT=true;

INFO_SYSTEM_TYPE='0';

INFO_USE_SEARCH_IP_CONFLICT=true;
